### ISSUE TITLE
Add option to configure available timeout modes

### ISSUE THREAD

**Issue by nvllsvm** [abdalmoniem/Caffeinate#25]
I want the ability to disable all timeout modes except for infinity. This would allow the quick tile to function as a toggle between off and always on.

**Comment by abdalmoniem** [comment]
done in 2387650d2f8c30253219babf4f79dde4f75d1843 ([tag v1.4.0](https://github.com/abdalmoniem/Caffeinate/tree/v1.4.0)), check release [v1.4.0](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.4.0)
