### ISSUE TITLE
Fastlane screenshots

### ISSUE THREAD

**Issue by IzzySoft** [abdalmoniem/Caffeinate#41]
Could the screenshots please be cleaned up a bit? 23 is a bit much:

* 16-23 are in the wrong place, they are not `en-US`
* a lot of screenshots are "almost-duplicates" where one needs to closely look to see the difference (e.g. 2 & 3, 10 & 13-15)

I'd enable pulling them to IzzyOnDroid with each new release, but because of the current state have left that disabled.

Thanks in advance!

**Comment by abdalmoniem** [comment]
sure, I'll clean them soon.

**Comment by IzzySoft** [comment]
Please don't forget. Before cleaned up, we cannot enable them at IzzyOnDroid :wink:

**Comment by abdalmoniem** [comment]
done in 985b29377b0b09cb4fd94c34ff7d31bf0d610c9a

**Comment by IzzySoft** [comment]
Thanks! Enabled here then – i.e. starting with the next release, they'll be pulled along.
