### ISSUE TITLE
make choice of timeouts more flexible

### ISSUE THREAD

**Issue by DJCrashdummy** [abdalmoniem/Caffeinate#42]
this is more or less a follow up on #25:
it would be nice to not just be able to en- or disable a hand full of pre-set timeouts, but also to add user defined timeouts (and for sure remove any of them).

**Comment by abdalmoniem** [comment]
fixed in commit ccc3710e41c8861cd62e30dbd0f3ab848ba0caca and included in release #v1.5.0

**Comment by abdalmoniem** [comment]
implemented in ccc3710e41c8861cd62e30dbd0f3ab848ba0caca, please check debug build [#335](https://github.com/abdalmoniem/Caffeinate/actions/runs/11624517927) for debug artifacts or download the [debug apk](https://github.com/abdalmoniem/Caffeinate/actions/runs/11624517927/artifacts/2131829375) directly to test

**Comment by abdalmoniem** [comment]
will close due to lack of feedback.
