### ISSUE TITLE
dimming buttons/slider contradict each other

### ISSUE THREAD

**Issue by DJCrashdummy** [abdalmoniem/Caffeinate#44]
i'm not 100% sure where the bug really is (at the main activity or the notification), but at least they do not match!

it seems that in the notification the "enable/disable dimming" button does the opposite: when it states "enable dimming" (which is IMHO an indicator that it is currently disabled), in the app the "allow dimming" slider is on and vice versa.

**Comment by abdalmoniem** [comment]
fixed in ccc3710e41c8861cd62e30dbd0f3ab848ba0caca ([tag v1.5.0](https://github.com/abdalmoniem/Caffeinate/tree/v1.5.0)), check release [v1.5.0](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.5.0)
