### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [abdalmoniem/Caffeinate#47]
Because the apk name is different from older versions... Could you please fix it?

**Comment by abdalmoniem** [comment]
sorry about that, but it is necessary to keep the current file naming scheme for consistency in differentiating between debug and release builds. the package name has not change though, so it should be compatible with previous releases.

please check and let me know.

**Comment by linsui** [comment]
Ah, so this is not a typo and will be kept for future versions?

**Comment by abdalmoniem** [comment]
yes

**Comment by linsui** [comment]
Could you please remove frosting block 'Dependency metadata'? It's signed by Google's public key so others can't read it.

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

**Comment by abdalmoniem** [comment]
updated [app/build.gradle.kts](https://github.com/abdalmoniem/Caffeinate/commit/f70475aa00c47a714bae0db758b6234c13fdf042#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46) in f70475aa00c47a714bae0db758b6234c13fdf042 ([tag v1.6.0](https://github.com/abdalmoniem/Caffeinate/tree/v1.6.0)), check release [v1.6.0](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.6.0)

**Comment by linsui** [comment]
Thanks!
