### ISSUE TITLE
[BUG] Stuck in theme choice

### ISSUE THREAD

**Issue by HarriBuh** [abdalmoniem/Caffeinate#49]
![markup_1000029685.png](https://github.com/user-attachments/assets/0c0fc7e8-0bc0-4c44-abaf-ac0a26277419)

I opened it, I chose it and it won't disappear, no matter what I do:

- Clicking anywhere on the screen
- Using the "back/ return"-gesture 

Google Pixel 7
Android 15

Edit: I just noticed, there IS a submit button at the very bottom of the popup, but it's unreachable/ hardly reachable.
Maybe you could place it higher?

**Comment by abdalmoniem** [comment]
fixed in https://github.com/abdalmoniem/Caffeinate/commit/4aef377ca0e5faeb487c3692d7c3ac41ae088671 ([tag v1.7.5](https://github.com/abdalmoniem/Caffeinate/tree/v1.7.5)), check release [v1.7.5](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.7.5)
