### ISSUE TITLE
[Bug] Cannot hold wakelock when app not on screen

### ISSUE THREAD

**Issue by lividhen** [abdalmoniem/Caffeinate#51]
### Description
The app cannot hold a wakelock or it is ignored when the app is not on screen. I'm not sure if this is an android 14 issue or a oneui 6 issue, but my guess is the latter. The app still functions in multi window and split screen if the app is not focused.

### Steps to Reproduce
1. Enable the app through the in app button or quick setting tile.
2. Wait for your default screen timeout.
3. Observe the device fall asleep at the default screen timeout.

### Expected Behavior
Screen stays awake until app timeout.

### Actual Behavior
Screen times out before app timeout.

### Screenshots or Videos
If applicable, add screenshots or a video to help illustrate the problem.

### Environment Details
Provide details about the environment where this issue occurred.

- **App Version:** 1.7.5
- **Android Version:** Android 14 (Oneui 6.1)
- **Device Model:** Samsung Galaxy Z Flip 5
- **Rooted or Non-Rooted:** non rooted
- **Screen Orientation:** N/A

### Log Output
If available, include any relevant log output. Use `adb logcat` to capture logs, if possible.
Or use [LogFox](https://apt.izzysoft.de/fdroid/index/apk/com.f0x1d.logfox) to capture logs from the device.

```plaintext
Paste logs here
```
(Could only find mentions of Bluetooth wake lock, not sure if relevant)

### Possible Solution
Using a screen overlay similar to tasker running some background tasks or a light filter (eg twilight, screen dimmer)

**Comment by abdalmoniem** [comment]
fixed in https://github.com/abdalmoniem/Caffeinate/commit/dc674e25828e93cf86dcf440f6e01a0c9bfd80b3 ([tag v1.8.0](https://github.com/abdalmoniem/Caffeinate/tree/v1.8.0)), check release [v1.8.0](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.8.0)
