### ISSUE TITLE
[Bug] The latest version of Caffeinate is not available on F-Droid

### ISSUE THREAD

**Issue by Korb** [abdalmoniem/Caffeinate#54]
The latest version is on Github: [1.8.0 (2024-11-14)](https://github.com/abdalmoniem/Caffeinate/releases/tag/v1.8.0)
The latest version is on IzzyOnDroid F-Droid Repo: 1.8.0 (2024-11-14)
The latest version is on F-Droid: [1.7.5](https://f-droid.org/en/packages/com.hifnawy.caffeinate/) (**2024-11-14**)

[Screenshot](https://drive.google.com/file/d/1G-86FM2zZvPjSvDV10j5RMsjD8kPOZJk/view) (Google Drive)

**Comment by abdalmoniem** [comment]
F-Droid and IzzyOnDroid pull releases from GitHub, they periodically check the repository for the latest release. It can take some time to trigger an update on F-Droid or IzzyOnDroid from GitHub.

I'll close this issue since nothing can be done on my side to fix the lag.
